PROGRAM Cyborg (input, output);

PROCEDURE Initialization;
	BEGIN
	END;

{----------------------------------------------}

PROCEDURE Get_Player_Input;
	BEGIN
	END;

{----------------------------------------------}

PROCEDURE Figure_AI_Response;
	BEGIN
	END;

{----------------------------------------------}

PROCEDURE Update_Screen;
	BEGIN
	END;

{==============================================}

BEGIN
END.
